### automation.yaml

#  Test Automation
- alias: Test Automation
  trigger:
    - platform: state
      entity_id: input_select.testselect
  action:
    - service: notify.telegram
      data:
        title: "Test Automation Status Change"
        message: "Status changed to {{ states.input_select.testselect.state }}"
#    - service: media_player.sonos_snapshot
#      data:
#        entity_id: media_player.kuche
#    - service: media_player.volume_set
#      data:
#        entity_id: media_player.kuche
#        volume_level: 0.3
#    - service: tts.google_say
#      entity_id: media_player.kuche
#      data:
#        message: "Test Status {{ states.input_select.testselect.state }}"
#    - delay: '00:00:02'
#    - service: media_player.sonos_restore
#      data:
#        entity_id: media_player.kuche
