### tumbler.yaml

input_select:
  tumbler_status:
    name: Tumbler Status
    options:
      - Running
      - Finished
      - "Off"
    initial: "Off"

switch:
  - platform: mystrom
    host: !secret mystrom4_ip
    name: mystrom4
    
sensor:
  - platform: template
    sensors:
      power_consumption_tumbler:
        unit_of_measurement: "W"
        value_template: >-
          {% if states.switch.mystrom4.attributes.current_power_w %}
            {{states.switch.mystrom4.attributes.current_power_w }}
          {% else %}
            0.0
          {% endif %}
      tumbler_status:
        value_template: "{{ states.input_select.tumbler_status.state }}"
        friendly_name: "Tumbler"

automation:
  - alias: Set the tumbler state to running when power consumption detected
    hide_entity: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.power_consumption_tumbler
        above: 50
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: input_select.tumbler_status
          state: "Finished"
        - condition: state
          entity_id: input_select.tumbler_status
          state: "Off"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.tumbler_status
          option: "Running"

  - alias: Set the tumbler state to finished when power consumption has dropped
    hide_entity: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.power_consumption_tumbler
        below: 5
        for:
          minutes: 2
    condition:
      condition: state
      entity_id: input_select.tumbler_status
      state: "Running"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.tumbler_status
          option: "Finished"

  - alias: Set tumbler state to off if power consumption is 0
    hide_entity: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.power_consumption_tumbler
        below: 0.1
        for:
          minutes: 2
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.tumbler_status
          option: "Off"